
services:
  db:
    image: mysql:8
    container_name: dk-prod-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dansekonnect_db
      MYSQL_USER: adminkonnect
      MYSQL_PASSWORD: password
    volumes:
      - db_prod_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile-prod
    container_name: dk-prod-backend
    ports:
      - "8082:80"
    depends_on:
      - db
    environment:
      ENVIRONMENT: prod
      DATABASE_URL: mysql://adminkonnect:password@db:3306/dansekonnect_db

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile-prod
    container_name: dk-prod-frontend
    ports:
      - "8084:80"
    environment:
      ENVIRONMENT: prod
      VITE_BACKEND_URL: http://dk-prod-backend:80

volumes:
  db_prod_data:
