version: '3.8'

services:
  db:
    image: mysql:8
    container_name: dk-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dansekonnect_db
      MYSQL_USER: adminkonnect
      MYSQL_PASSWORD: password
    
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./src/backend
    container_name: dk-backend
    ports:
      - "${BACKEND_PORT:-8081}:80"
    depends_on:
      - db
    environment:
      LISTEN_PORT: 80
      LISTEN_IP: 0.0.0.0
      DATABASE_URL: mysql://adminkonnect:password@db:3306/dansekonnect_db

  frontend:
    build:
      context: ./src/frontend
    container_name: dk-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://dk-backend:80

volumes:
  db_data:
