
services:
  db:
    image: mysql:8
    container_name: dk-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dansekonnect_db
      MYSQL_USER: adminkonnect
      MYSQL_PASSWORD: password
    volumes:
      - db_dev_data:/var/lib/mysql

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile-dev
    container_name: dk-dev-backend
    ports:
      - "8083:80"
    environment:
      ENVIRONMENT: dev
      DATABASE_URL: mysql://adminkonnect:password@db:3306/dansekonnect_db
    volumes:
      - ./src/backend:/app      
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile-dev
    container_name: dk-dev-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend:/app     
    depends_on:
      - backend

volumes:
  db_dev_data:
